### ISSUE TITLE
Books not related to tattoo?

### ISSUE THREAD

**Issue by gschivley** [annafelicity/predicting_popularity#1]
My wife is getting excited about Moms Can Code, which prompted me to check out your work on GitHub. Congrats on the journey you've been on over the past few years!

While reading through your final modeling notebook I noticed that "The Berenstain Bears Meet Santa Bear" is the 5th record in your dataset, and wondered how it could have made it into a list of books related to tattoos. A WorldCat search reveals that the notes section has: "Includes stickers, **tattoos**, and a memory card game!"--Cover.

Have you thought about removing books that are obviously not tattoo related?

**Comment by annafelicity** [comment]
Hi there! Somehow I missed this note. Yes, future tweaks of the model will do a better job of removing non-tattoo books. There are some removed now, but it is not perfect, as you noticed. One easy way to remove them would be to take out the juvenile audience ones, which tend to be noted in a way that they are easy to id. Thanks for your input!

**Comment by gschivley** [comment]
In retrospect, this was an unnecessary comment. Sorry about that :)
